### PR TITLE
F/https

### PR DESCRIPTION
**Pull request by faxm0dem**
add support for username/password basic auth, and https

### CODE REVIEW

**Comment by faxm0dem** [comment]
hi there is there anything I can do to move forward?

**Comment by cygnusb** [comment]
We cannot accept these changes. Your changes modify the default indent of the code (autopep8). lint fixes are partly ok, but we want to stick with longer line numbers.

See also: https://gist.github.com/MarcDiethelm/7303312 mainly: "Follow the code style of the project, including indentation."

And the authentication change modifies the ElasticsearchAPI init call, which we also cannot accept. 

Please only contribute the functional change and do not change the init call syntax (Options defaulting to None would be ok)
`def __init__(self, host, port, prefix, scheme='http', username=None, password=None):`

**Comment by faxm0dem** [comment]
I tried to address your concerns. Please review them.

**Comment by cygnusb** [comment]
Looks better. But the --insecure option seems to not be used at all and you are always creating an unverified ssl connection.

**Comment by faxm0dem** [comment]
I'm sorry about that WIP part that I missed.
I'll fix this ASAP, thanks!

**Comment by faxm0dem** [comment]
Hi anything I can do to help merge this?

**Comment by p3dda** [comment]
> the --insecure option seems to not be used at all and you are always creating an unverified ssl connection.

This issue has not yet been fixed in your pull request.

**Comment by faxm0dem** [comment]
:man_facepalming: I'm really sorry about that
Totally my fault, sorry for poking you for nothing.
I'll poke you again as soon as I'm done :pray:

**Comment by faxm0dem** [comment]
I just realised this is still python2. Do you have plans to upgrade to python3 ?

**Comment by faxm0dem** [comment]
I added the proper ssl context handling, and also implemented usercert auth.
The python3 changes are minimal, so can easily be changed if you still require python2

**Comment by cygnusb** [comment]
I am sorry, but we cannot accept it this way. You have now also added changes that require Python 3. Base code and documentation, rpm Specfile... Everything is based on Python 2.
So in generall Pull request on github projects should not mix different features within one pull request.
Python 3 would be nice, but this should be a seperate pull request. Dropping Python 2 support is fine from out side, but you might consider adding Python2/3 support using Package six. We are not using this plugin anymore. So we cannot do any testing or porting ourselves

**Comment by faxm0dem** [comment]
Are you saying you're not using it anymore internally, but still supporting the code ?
I will make a separate PR for python3

**Comment by faxm0dem** [comment]
I reverted the python3 changes.
Now this PR is a pure https+auth implementation
Tested with python27
I'll open another PR for python3 later

**Comment by cygnusb** [comment]
> Are you saying you're not using it anymore internally, but still supporting the code ?

we stopped using it end of last year. If you like I can transfer the repo to you.

> I will make a separate PR for python3

Ok, great. Thanks!

**Pull request merged**
