### PR TITLE
add requirements

### PR DESCRIPTION
**Pull request by faxm0dem**
makes deployment more natural :)

### CODE REVIEW

**Comment by cygnusb** [comment]
I think that is not correct. See https://caremad.io/posts/2013/07/setup-vs-requirement/
And in addition arpparse, json, ... are all part of the standard library?!?

**Comment by faxm0dem** [comment]
I agree with standard libs, but not 'nagiosplugin'. This should be in requirements, shouldn't it?

**Comment by cygnusb** [comment]
It is included by -e .

See provided link which I cite here: "have abstract dependencies in your setup.py and concrete dependencies in your requirements.txt but you don’t want to need to maintain two separate lists which will inevitably go out of sync. As it turns out pip requirements file have a construct to handle just such a case. Given a directory with a setup.py inside of it you can write a requirements file that looks like:"

**Comment by faxm0dem** [comment]
Thanks ! Now I learned what cryptic  `-e .` means :-)

**Pull request closed without merging**
